# Generated by Django 4.2.6 on 2024-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='date_time',
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
