# Generated by Django 4.2.6 on 2024-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_interviewee_alter_booking_interviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
