# Generated by Django 5.0.4 on 2024-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interview_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='adaptability',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='communication_skills',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='competency',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_effectiveness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='preparation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='professionalism',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='time_management',
            field=models.FloatField(null=True),
        ),
    ]
