# Generated by Django 4.2.6 on 2024-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedback_adaptability_feedback_communication_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='overall_effectiveness',
            field=models.TextField(null=True),
        ),
    ]
